# Generated by Django 5.1.2 on 2024-10-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
